apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-init
data:
  init.sh: |
    #!/bin/bash
    sleep 10
    if [[ $(hostname) == *-0 ]]; then
      until mongo --eval "rs.initiate()"; do
        echo "Waiting for primary to initialize..."
        sleep 5
      done
      
      sleep 10
      mongo admin --eval '
        db.createUser({
          user: "'${MONGO_INITDB_ROOT_USERNAME}'",
          pwd: "'${MONGO_INITDB_ROOT_PASSWORD}'",
          roles: [{ role: "root", db: "admin" }]
        })'
    else
      until mongo --host {{ .Values.service.name }}-0.{{ .Values.service.name }}-headless --eval "rs.status()"; do
        echo "Waiting for primary..."
        sleep 5
      done
      mongo --host {{ .Values.service.name }}-0.{{ .Values.service.name }}-headless --eval "rs.add('$(hostname)')"
    fi