apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-replicaset.fullname" . }}
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
    - port: 27017
      name: mongo
  selector:
    app: mongodb
