apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-exec
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-exec-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-exec-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: mongodb-exec
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mongodb-exec-role
  apiGroup: rbac.authorization.k8s.io
