apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.service.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.service.name }}