apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongodb-replicaset.fullname" . }}
  labels:
    app: mongodb
spec:
  serviceName: {{ include "mongodb-replicaset.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: copy-keyfile
          image: busybox
          command:
            - "sh"
            - "-c"
            - |
              cp /tmp/keyfile/keyfile /etc/mongodb/keyfile && chmod 0400 /etc/mongodb/keyfile
          volumeMounts:
            - name: keyfile-secret
              mountPath: /tmp/keyfile
            - name: keyfile-copy
              mountPath: /etc/mongodb
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["mongod"]
          args:
            - "--replSet"
            - "rs0"
            - "--bind_ip_all"
            - "--keyFile"
            - "/etc/mongodb/keyfile"
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: datadir
              mountPath: /data/db
            - name: keyfile-copy
              mountPath: /etc/mongodb
              readOnly: true
            - name: rs-init-script
              mountPath: /config
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    exec > /proc/1/fd/1 2>/proc/1/fd/2
                    set -x
                    sleep 10;                 
                    for i in $(seq 1 30); do
                      if mongo --host localhost --eval "db.adminCommand('ping')" --quiet; then
                        echo "Mongo is up...";
                        break;
                      fi;
                      echo "Waiting for mongod to be ready ($i/30)...";
                      sleep 5;
                    done;
                    echo "Running replica set initiation script...";
                    mongo --host localhost /config/init.js || true;
                    exit 0
      volumes:
        - name: keyfile-secret
          secret:
            secretName: {{ .Values.mongoKeyfile.secretName | quote }}
            defaultMode: 0400
        - name: keyfile-copy
          emptyDir: {}
        - name: keyfile
          secret:
            secretName: {{ .Values.mongoKeyfile.secretName | quote }}
            defaultMode: 0400
        - name: rs-init-script
          configMap:
            name: mongodb-rs-init
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
